================== EDA================
pandas             :Data frame or daa applications
numpy              : numerical python
matplotlib         :for plot graphs
seaborn            : for plot graphs
bokhe              : for plots
plotly             : for plots
============= Machine learning=========
scikit learn (sklearn)  : ML models
stats                   : statical models
============= Data retrival from sql scrapping===========
sqlite                : connect with database
Beautiful soop        : Scrp the data from website
websocket             : scrap
=================deep learning computer vision =============
tensorflow             :google
keras                  : DL models
openCV                 :image operations
pillow(pill)           :image operations
pytorch                :Facebook
pretrined model 
   VGG16
   Mobilenet
   RESNET
   RCNN
   MASKRCNN
   FASTERCNN
   YOLO
=====================Natural language process===============
MLTK               : NATURAL LANGUAGE PROCESS
scipy
Word2vec(how words will converted into vectors)
GloVE
wordcloux
==============Hugging face=====================
Trnsformers   : BERT

====================GenAI models============
OpenAIbMicrosoft : GPT models
Google    : Gemni
Amazon       : Q
meta Facebook   :meta AI
Apple:
ALL are having different packages
==================== lang chain================
LangChain Framework


=================Deployments=============
Flask
streamlit
Django

===============MLops===============
Mlflow
Kubaflow
Azure AI services :azure packages
GCP           :GCP packages





**Step 1**

we will create a data frame

In [5]:
import pandas as pd
d1=pd.DataFrame()
d1

Empty DataFrame
Columns: []
Index: []

In [6]:
type(d1)

pandas.core.frame.DataFrame

**Step-2**
provide data


In [ ]:
names=['tarun','surenda','mohit']
pd.DataFrame(names)

In [7]:
names=['tarun','surenda','mohit']
age=[20,21,22]
city=['hyd','blr','chennai']
pd.DataFrame(zip(names,age,city))

0   1        2
0    tarun  20      hyd
1  surenda  21      blr
2    mohit  22  chennai

**step-3**
**provide the column names**

In [8]:
pd.DataFrame(zip(names,age,city),columns=['Names','age','city'])

Names  age     city
0    tarun   20      hyd
1  surenda   21      blr
2    mohit   22  chennai

In [12]:
import pandas as pd
pd.DataFrame(zip(names,age),index=city,columns=['Names','age'])
pd

<module 'pandas' from 'C:\\Users\\HP\\AppData\\Local\\anaconda3\\Lib\\site-packages\\pandas\\__init__.py'>

In [7]:
#pd.DataFrame(zip(names,age,city),index =[ i for i in range(1,3)],columns=['Names','age','city'])

In [18]:
import pandas as pd1
name=['hai','hello','sam']
age=[10,20,30,40]
city=["hyd","chennai","blr"]
pd1.DataFrame(zip(name,age,city))

0   1        2
0    hai  10      hyd
1  hello  20  chennai
2    sam  30      blr

In [23]:
# if you want to add a new coloumn 

import pandas as pd1
name=['hai','hello','sam']
age=[10,20,30,40]
city=["hyd","chennai","blr"]
d1=pd1.DataFrame(zip(name,age,city))
salary=[10000,25000,60000]
d1['salary']=salary
d1

0   1        2  salary
0    hai  10      hyd   10000
1  hello  20  chennai   25000
2    sam  30      blr   60000

In [17]:
# create a emty data frame
# create 3 list using list comprehension
#list1= a values from 1 to 10
#list2= square of 1 to 10
#list3= cube of 1 to 10
import pandas as pd
list1=[i for i in range(1,11)]
list2=[i*i for i in range(1,11)]
list3=[i*i*i for i in range(1,11)]

df=pd.DataFrame()
df['X']=list1
df['Y']=list2
df['Z']=list3
df


X    Y     Z
0   1    1     1
1   2    4     8
2   3    9    27
3   4   16    64
4   5   25   125
5   6   36   216
6   7   49   343
7   8   64   512
8   9   81   729
9  10  100  1000

In [18]:
# update the already existed column

D=[(i+1) for i in range(1,11)]
df['Z']=D
df

X    Y   Z
0   1    1   2
1   2    4   3
2   3    9   4
3   4   16   5
4   5   25   6
5   6   36   7
6   7   49   8
7   8   64   9
8   9   81  10
9  10  100  11

In [39]:
# how to check the number of columns
df.columns

Index(['X', 'Y', 'Z'], dtype='object')

In [20]:
# drop a colunm
df11=df.drop('Z',axis=1)
df11

X    Y
0   1    1
1   2    4
2   3    9
3   4   16
4   5   25
5   6   36
6   7   49
7   8   64
8   9   81
9  10  100

In [28]:
#drop a column
print(df)
df22=df.drop([0,1],axis=1)
df22

    X    Y   Z
0   1    1   2
1   2    4   3
2   3    9   4
3   4   16   5
4   5   25   6
5   6   36   7
6   7   49   8
7   8   64   9
8   9   81  10
9  10  100  11


KeyError: '[0, 1] not found in axis'

In [44]:
type(df['X'])
print(df['X'])
# series type
# no coloumn name display


0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
Name: X, dtype: int64


In [45]:
# data frame type
type(df[['X']])
print(df[['X','Y']])

    X    Y
0   1    1
1   2    4
2   3    9
3   4   16
4   5   25
5   6   36
6   7   49
7   8   64
8   9   81
9  10  100


In [48]:
df.X

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
Name: X, dtype: int64

In [56]:
df['X'].values

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int64)

- All vales caome in an array
- array means it is a list of elements only represents using numpy package
- generally elements present in 4 ways
      - list: basic representation
      = Numpy array: Array with numpt package
      - Tensors : tensor flow package
      - torch : pytorchpackage

In [57]:
list1=[1,2,3]
list1

[1, 2, 3]

In [58]:
import numpy as np
np.array(list1)

array([1, 2, 3])

In [61]:
#tensor([1,2,3,4])

In [62]:
list1=[1,2,3,4]
list2=[10,20,30,40]
list1+list2

[1, 2, 3, 4, 10, 20, 30, 40]

In [63]:
l1=np.array(list1)
l2=np.array(list2)
l1+l2

array([11, 22, 33, 44])

In [64]:
df['X'].values

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int64)

In [67]:
df['XX']=df['X'].values
df

X    Y   Z  XX
0   1    1   2   1
1   2    4   3   2
2   3    9   4   3
3   4   16   5   4
4   5   25   6   5
5   6   36   7   6
6   7   49   8   7
7   8   64   9   8
8   9   81  10   9
9  10  100  11  10

# how to save the dataframe
-Data frame scan save in two formats
    - csv: comma seperated value
    - xlsx: excel format
- in order to save any data
    -  where you  want to save :directory name
    - what is the name of the file for storing
    - what is the extension

- 

**Case 1: saving file at same location .no need to provide directory path**
**directly give only name of file and extension**

In [85]:
df.to_csv('Data1.csv')
df.to_excel('Data1.xlsx')

In [86]:
# how to read the data frame
import pandas as pd
pd.read_csv('Data1.csv')


X    Y   Z  XX
0   1    1   2   1
1   2    4   3   2
2   3    9   4   3
3   4   16   5   4
4   5   25   6   5
5   6   36   7   6
6   7   49   8   7
7   8   64   9   8
8   9   81  10   9
9  10  100  11  10

In [87]:
import pandas as pd
pd.read_excel('Data1.xlsx')

X    Y   Z  XX
0   1    1   2   1
1   2    4   3   2
2   3    9   4   3
3   4   16   5   4
4   5   25   6   5
5   6   36   7   6
6   7   49   8   7
7   8   64   9   8
8   9   81  10   9
9  10  100  11  10

In [ ]:
# how to avoid index coloum
while we save automatically a new coloumn will create that we need to avoid

TypeError: read_csv() got an unexpected keyword argument 'index'

In [89]:
df.to_csv('Data1.csv',index=False)
df.to_excel('Data1.xlsx',index=False)
pd.read_csv('Data1.csv')

X    Y   Z  XX
0   1    1   2   1
1   2    4   3   2
2   3    9   4   3
3   4   16   5   4
4   5   25   6   5
5   6   36   7   6
6   7   49   8   7
7   8   64   9   8
8   9   81  10   9
9  10  100  11  10